name: Release Build

on:
  push:
    branches:
      - release

# Add permissions block
permissions:
  contents: write
  packages: write

jobs:
  # android-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '18.19.0'
  #         cache: 'npm'

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Setup EAS
  #       uses: expo/expo-github-action@v8
  #       with:
  #         eas-version: latest
  #         token: ${{ secrets.EXPO_TOKEN }}

  #     - name: Build Android APK
  #       id: eas-build
  #       run: |
  #         OUTPUT=$(eas build -p android --profile preview --non-interactive)
  #         APK_URL=$(echo "$OUTPUT" | grep -o 'https://expo.dev/artifacts/eas/[^[:space:]]*\.apk')
  #         echo "APK_URL=$APK_URL" >> $GITHUB_ENV

  #     - name: Download APK
  #       run: |
  #         curl -L -o compass.apk "${{ env.APK_URL }}"

  #     - name: Get Version
  #       id: package-version
  #       run: |
  #         VERSION=$(node -p "require('./package.json').version")
  #         echo "VERSION=$VERSION" >> $GITHUB_ENV

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:v${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  create-release:
    # needs: [android-build, docker-build]
    needs: [docker-build]
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: compass.apk
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: |
            Android APK and Docker image are now available.

            Docker image:
            - `ghcr.io/${{ github.repository }}:latest`
            - `ghcr.io/${{ github.repository }}:v${{ env.VERSION }}`
            
            To pull and run the Docker image:
            ```bash
            docker pull ghcr.io/${{ github.repository }}:latest
            docker run -p 80:80 ghcr.io/${{ github.repository }}:latest
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 