name: Release Build

on:
  push:
    branches:
      - release

permissions:
  contents: write
  packages: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        
      - name: Get Version
        id: package-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  docker-build:
    needs: setup
    uses: ./.github/workflows/docker-build.yml
    with:
      version: ${{ needs.setup.outputs.version }}
    secrets: inherit

  web-deploy:
    needs: setup
    uses: ./.github/workflows/web-deploy.yml
    secrets: inherit

  create-release:
    needs: [setup, docker-build, web-deploy]
    uses: ./.github/workflows/create-release.yml
    with:
      version: ${{ needs.setup.outputs.version }}
    secrets: inherit