name: Release Build

on:
  push:
    branches:
      - release

permissions:
  contents: write
  packages: write

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get Version
        id: package-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  docker-build:
    needs: get-version
    uses: ./.github/workflows/docker-build.yml
    with:
      version: ${{ needs.get-version.outputs.version }}
    secrets: inherit

  windows-build:
    needs: get-version
    uses: ./.github/workflows/windows-build.yml
    with:
      version: ${{ needs.get-version.outputs.version }}

  web-deploy:
    needs: get-version
    uses: ./.github/workflows/web-deploy.yml
    secrets: inherit

  create-release:
    needs: [get-version, docker-build, web-deploy, windows-build]
    uses: ./.github/workflows/create-release.yml
    with:
      version: ${{ needs.get-version.outputs.version }}
    secrets: inherit