name: Create Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Build
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: windows-build

      - name: Download Linux Build
        uses: actions/download-artifact@v4
        with:
          name: linux-build
          path: linux-build

      - name: Check if build files are available
        run: |
          echo "Windows Build:"
          ls windows-build/msi
          ls windows-build/nsis
          echo "Linux Build:"
          ls linux-build/deb
          ls linux-build/rpm
          ls linux-build/appimage

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ inputs.version }}
          name: Release v${{ inputs.version }}
          body: |
            Docker image, Windows application, and Linux packages are now available.

            🐋 Docker image:
            - `ghcr.io/${{ github.repository }}:latest`
            - `ghcr.io/${{ github.repository }}:v${{ inputs.version }}`
            
            To pull and run the Docker image:
            ```bash
            docker pull ghcr.io/${{ github.repository }}:latest
            docker run --network host -p 80:80 ghcr.io/${{ github.repository }}:latest
            ```

            Then you can use compass by visiting "http://localhost" in your browser.
            This image comes pre-packaged with a proxy server that allows you to use Ollama without any configuration.

            🪟 Windows Application:
            Download the installer from the assets below. Both MSI and EXE installers are provided.

            🐧 Linux Packages:
            - DEB package for Debian/Ubuntu-based distributions
            - RPM package for Red Hat/Fedora-based distributions
            - AppImage for universal Linux compatibility
          draft: false
          prerelease: false
          files: |
            windows-build/msi/compass*.msi
            windows-build/nsis/compass*.exe
            linux-build/deb/compass*.deb
            linux-build/rpm/compass*.rpm
            linux-build/appimage/compass*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}