name: Build Multi-Platform

on:
  push:
    branches: [ experiment/windows-build ]
  pull_request:
    branches: [ experiment/windows-build ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
          cache: 'npm'

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.3
        with:
          vs-version: latest
          msbuild-architecture: x64

      - name: Install dependencies
        run: npm install

      - name: Skip dependency check and build directly
        run: |
          # Skip the problematic dependency check
          npx react-native autolink-windows

      - name: Build Windows Desktop with explicit SDK
        run: |
          # Use the Windows 11 SDK that's available on windows-2022 runners
          npx react-native run-windows --release --no-deploy --no-launch --arch x64 --msbuildprops "WindowsTargetPlatformVersion=10.0.22621.0;PlatformToolset=v143"
        shell: powershell

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: windows/x64/Release/
        if: success()